Update build-turnip.yml

diff --git a/.github/workflows/build-turnip.yml b/.github/workflows/build-turnip.yml
--- a/.github/workflows/build-turnip.yml
+++ b/.github/workflows/build-turnip.yml
@@ -23,21 +23,29 @@ jobs:
            bash ./turnip_builder_a9.sh
            echo "VERSION=$(cat $GITHUB_WORKSPACE/turnip_workdir/mesa-main/VERSION)" >> $GITHUB_ENV
            echo "DATE=$(date +'%d%m%Y')" >> $GITHUB_ENV
+      continue-on-error: true
            
-    - name: Upload a Build Artifact
+    - name: Upload Logs
       uses: actions/upload-artifact@v4
       with:
         name: Upload meson and ninja logs for debugging
         path: |
           turnip_workdir/ninja_log
           turnip_workdir/mesa-main/build-android-aarch64/meson-logs/meson-log.txt
+          
+    - name: Fail if build failed
+      if: steps.Exexute build script.outcome == 'failure'
+      run: |
+            echo "Build failed. Logs were uploaded."
+            exit 1
   #  - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
      #   name : Turnip-Magisk-${{ env.VERSION }}-${{github.run_number}}
       #  path : turnip_workdir/turnip_module
-    - name: Upload a Build Artifact
+    - name: Upload AdrenoTools driver
       uses: actions/upload-artifact@v4
+      if: success()
       with:
         name : Turnip-AdrenoTools-${{ env.VERSION }}-${{ env.DATE }}
         path : |
